package com.tudagroup.lecturerate.backend.entity;

import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.Date;

/**
 * This class represents a review that users can give for the individual courses
 *
 * @author sijunkwon
 */
@Entity
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @ManyToOne
    private UserAccount userAccount;
    @ManyToOne
    private Course course;
    @CreationTimestamp
    private Date createdAt;
    private Short rating;
    private String comment;
    @Enumerated(EnumType.ORDINAL)
    private Difficulty difficulty;

    public Review() {

    }

    /**
     * @param id          an autogenerated number
     * @param userAccount the author of the review
     * @param course      the course the review is referring to
     * @param createdAt   when the review was written
     * @param rating      the overall rating for the course given by the author
     * @param comment     text of the review for the course
     * @param difficulty  rating for the difficulty of the course (easy, medium or hard)
     */
    public Review(Long id, UserAccount userAccount, Course course, Date createdAt, Short rating, String comment, Difficulty difficulty) {
        this.id = id;
        this.userAccount = userAccount;
        this.course = course;
        this.createdAt = createdAt;
        this.rating = rating;
        this.comment = comment;
        this.difficulty = difficulty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserAccount getUserAccount() {
        return userAccount;
    }

    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Short getRating() {
        return rating;
    }

    public void setRating(Short rating) {
        this.rating = rating;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Difficulty getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(Difficulty difficulty) {
        this.difficulty = difficulty;
    }
}
